site_name: "OpenWave docs"
site_description: "OpenWave Documentatie"
site_url: "https://open-wave-community.github.io/"
repo_url: "https://github.com/open-wave-community/docs"
edit_uri: blob/main/docs/
repo_name: "open-wave-community/docs"

theme:
  name: material
  features:
    - content.action.edit
    - navigation.tabs
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: blue
    accent: orange

docs_dir: "docs"
extra_css:
  - css/style.css

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"

watch:
  - mkdocs_gen_files

plugins:
  - search
  - gen-files:
      scripts:
        - gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  nav:
    absolute_links: ignore
