site_name: "OpenWave docs"
site_url: "https://open-wave-community.github.io/docs"
repo_url: "https://github.com/open-wave-community/docs.open-wave.nl"
edit_uri: blob/main/docs/
docs_dir: docs/

theme:
  name: material
  language: nl
  features:
    - content.action.edit
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.indexes
    - navigation.prune
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: blue
    accent: orange

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - nl2br
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: "¤"

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - callouts

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
